include $(CLEAR_VARS)
LOCAL_MODULE := libGLES_ufo_intel7_5
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/egl/
LOCAL_MODULE_STEM := libGLES_intel7_5
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES := $(TARGET_BOARD_PLATFORM)/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := curd
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT_EXECUTABLES)/
LOCAL_SRC_FILES := $(TARGET_BOARD_PLATFORM)/curd
include $(BUILD_PREBUILT)
